# Generated by Django 4.1.7 on 2023-03-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_free', models.IntegerField()),
                ('mon_tope', models.IntegerField()),
                ('msg_global', models.CharField(max_length=100)),
                ('status_adm', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_loteria', models.IntegerField()),
                ('no_animal', models.CharField(max_length=2)),
                ('fecha_lot', models.DateField()),
                ('hr_gen_nu', models.TimeField()),
                ('serv_gen', models.CharField(max_length=10)),
                ('loteria', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_emp', models.CharField(max_length=20)),
                ('nom_pro', models.CharField(max_length=20)),
                ('ape_pro', models.CharField(max_length=20)),
                ('tlf_pro', models.IntegerField()),
                ('cor_pro', models.EmailField(max_length=254)),
                ('fec_reg', models.DateField()),
                ('fec_venc', models.DateField()),
                ('blq', models.IntegerField()),
            ],
        ),
    ]
